In [1]:
#order of Matrix | shape of matrix
import numpy as np

# Create a sample array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Check the shape of the array
shape = arr.shape

print("Shape of the array:", shape)



Shape of the array: (2, 3)


In [18]:
import numpy as imran
arr = imran.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]


In [22]:
shape = arr.shape
print(f"Shape of array is {shape} ****** Here Row is {shape[0]} and column is {shape[1]} it represent as RxC or m x n =({shape[0]}X{shape[1]}) and reading m by n")

Shape of array is (4, 3) ****** Here Row is 4 and column is 3 it represent as RxC or m x n =(4X3) and reading m by n


In [17]:
# Here 2 is Rows and 3 is columns

In [28]:
import numpy as np

# Define a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Find the position of value 5
indices = np.where(matrix == 8)

# Print the indices
print("Position of value 5:", indices)
print("\nPosition of value 5:")
print("Row index:", indices[0][0])
print("Column index:", indices[1][0])


Position of value 5: (array([2], dtype=int64), array([1], dtype=int64))

Position of value 5:
Row index: 2
Column index: 1


In [29]:
import numpy as np

# Define a sample matrix
matrix = np.array([[1, 2, 3]])

# Check if it's a row matrix
if matrix.shape[0] == 1:
    print("The matrix is a row matrix.")
else:
    print("The matrix is not a row matrix.")


The matrix is a row matrix.


In [38]:
import numpy as np

# Define a sample matrix
matrix = np.array([[1, 2, 3]])
print(matrix.shape)

# Check if it's a row matrix
if matrix.shape[0] == 1:
    print("The matrix is a row matrix.")
else:
    print("The matrix is is not row matrix.")

(1, 3)
The matrix is a row matrix.


In [40]:
def rowMatrix(r):
    if r.shape[0] == 1:
        print("The matrix is a row matrix.")
    else:
        print("The matrix is is not row matrix.")
rowMatrix(matrix)        

The matrix is a row matrix.


In [51]:
def ColumnMatrix(c):
    if c.shape[1] == 0:
        print(f"The matrix is a Column matrix order is {c.shape}.\n Total elements{c.size}")
    else:
        print(f"The matrix is not Column matrix order is {c.shape}.\nTotal elements {c.size}")
ColumnMatrix(matrix)

The matrix is not Column matrix order is (3, 3).
Total elements 9


In [44]:
import numpy as np

# Define a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Get the diagonal elements
diagonal_elements = np.diagonal(matrix)

# Print the diagonal elements
print("Diagonal elements of the matrix:", diagonal_elements)

Diagonal elements of the matrix: [1 5 9]
